name: Vortexa Auto Renew

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 */4 * *'   # 每4天执行一次（建议）

permissions:
  contents: write

jobs:
  renew-job:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run script
        env:
          VORTEXA_COOKIE: ${{ secrets.VORTEXA_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python renew_service.py

      - name: Upload screenshots if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: "*.png"

      - name: Update time.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "$(date +'%Y-%m-%d %H:%M:%S')" > time.txt

          git add time.txt
          if git diff --cached --quiet; then
            echo "no change"
          else
            git commit -m "⏱️ update time: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
